name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] ⌘ "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please fill out the following:
  - type: input
    id: environment
    attributes:
      label: Environment
      description: e.g. OS, Waybar version, Zig version
      placeholder: "macOS 12.3, Waybar v3.5, Zig 0.11.0-dev"
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe how to reproduce the issue
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: Any relevant output or stack trace
      placeholder: '```text\n[error message]\n```'
    validations:
      required: false