name: ⭐ Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["Enhancement", "Feature Request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide context:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature useful?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Implementation
      description: If you have ideas, describe how this might be done
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you considered?
    validations:
      required: false