name: ❓ General / Question
description: Ask a question or request clarification
title: "[Question] "
labels: ["Question"]
body:
  - type: markdown
    attributes:
      value: |
        Let us know your question:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Your question or request
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant background or attempts
    validations:
      required: false